name: Ubuntu-appimage

on:
  release:
    types: [created]  # Triggers on release created
  workflow_dispatch:

jobs:
  ubuntu-appimage:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install build essentials
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Install dependencies
      run: sudo apt install -y ffmpeg libfftw3-dev libopus-dev libopusfile-dev libvorbis-dev libchafa-dev libfreeimage-dev libavformat-dev libstb-dev libnotify-dev wget

    - name: Build code
      run: |
        make

    - name: Prepare AppDir
      run: |
        mkdir -p appdir/usr/bin
        chmod +x ./kew
        mv ./kew appdir/usr/bin/
        mkdir -p appdir/usr/lib

    - name: Verify AppDir Structure Before AppImage Creation
      run: |
        echo "Listing appdir structure before running appimagetool"
        ls -R appdir

    - name: Download and prepare appimagetool
      run: |
        wget -O appimagetool-x86_64.AppImage -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
        if [ ! -f appimagetool-*.AppImage ]; then
          echo "appimagetool download failed"; exit 1;
        fi          
        chmod +x appimagetool-*.AppImage

    - name: Deploy desktop file
      run: |
        ./appimagetool-*.AppImage deploy appdir/usr/share/applications/kew.desktop

    - name: Remove unnecessary libraries
      run: |
        rm appdir/lib/x86_64-linux-gnu/libavcodec*
        rm appdir/lib/x86_64-linux-gnu/libavformat*
        rm appdir/lib/x86_64-linux-gnu/libavutil*
        rm appdir/lib/x86_64-linux-gnu/libswres*

    - name: Create AppImage
      run: |
        mkdir -p output
        VERSION=$(./appdir/usr/bin/kew --version | awk -F": " 'FNR==6 {printf $NF}') ./appimagetool-*.AppImage ./appdir

    - name: Move and Rename kew AppImage
      run: |
        mv kew*.AppImage output/kew
        chmod +x output/kew      

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: kew appImage (glibc systems, most systems) 
        automatic_release_tag: stable
        prerelease: false
        draft: true
        files: |
          output/kew
        repo_token: ${{ secrets.GITHUB_TOKEN }}
