name: AlmaLinux-appimage

on:
  release:
    types: [created]  # Triggers on release created
  workflow_dispatch:

jobs:
  almalinux-appimage:
    runs-on: ubuntu-latest
    container:
      image: almalinux:9  # Use almalinux for compatibility

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Development Tools and EPEL repo
      run: |
        dnf -y update
        dnf -y groupinstall "Development Tools"
        dnf -y install epel-release
        dnf -y install wget

    - name: Add the RPM Fusion repo
      run: |
        dnf config-manager --set-enabled crb
        dnf install --nogpgcheck https://mirrors.rpmfusion.org/free/el/rpmfusion-free-release-$(rpm -E %rhel).noarch.rpm -y
        dnf install --nogpgcheck https://mirrors.rpmfusion.org/nonfree/el/rpmfusion-nonfree-release-$(rpm -E %rhel).noarch.rpm -y       

    - name: Install dependencies
      run: |
        dnf -y install ffmpeg ffmpeg-devel fftw-devel opus-devel opusfile-devel libvorbis-devel chafa-devel freeimage-devel \
                       libnotify-devel glibc-devel

    - name: Build code
      run: |
        make

    - name: Prepare AppDir
      run: |
        mkdir -p appdir/usr/bin
        chmod +x ./kew
        mv ./kew appdir/usr/bin/
        mkdir -p appdir/usr/lib

    - name: Verify AppDir Structure Before AppImage Creation
      run: |
        echo "Listing appdir structure before running appimagetool"
        ls -R appdir

    - name: Download and prepare appimagetool
      run: |
        wget -O appimagetool-x86_64.AppImage -c https://github.com/$(wget -q https://github.com/probonopd/go-appimage/releases/expanded_assets/continuous -O - | grep "appimagetool-.*-x86_64.AppImage" | head -n 1 | cut -d '"' -f 2)
        if [ ! -f appimagetool-*.AppImage ]; then
          echo "appimagetool download failed"; exit 1;
        fi          
        chmod +x appimagetool-*.AppImage

    - name: Deploy desktop file
      run: |
        ./appimagetool-x86_64.AppImage --appimage-extract-and-run deploy appdir/usr/share/applications/kew.desktop

    - name: Remove unnecessary libraries
      run: |
        rm appdir/usr/lib64/libavcodec*
        rm appdir/usr/lib64/libavformat*
        rm appdir/usr/lib64/libavutil*
        rm appdir/usr/lib64/libswres*

    - name: Create AppImage
      run: |
        mkdir -p output
        APPIMAGE_EXTRACT_AND_RUN=1 \
        ARCH=$(uname -m) \
        VERSION=$(./appdir/usr/bin/kew --version | awk -F": " 'FNR==6 {printf $NF}') \
        ./appimagetool-*.AppImage ./appdir

    - name: Move and Rename kew AppImage
      run: |
        mv kew*.AppImage output/kew
        chmod +x output/kew

    - name: Release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        title: kew appImage (glibc systems, most systems) 
        automatic_release_tag: stable-glibc
        prerelease: false
        draft: true
        files: |
          output/kew
        repo_token: ${{ secrets.GITHUB_TOKEN }}
