name: Build Check

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  ubuntu-build-check:
    name: Ubuntu Build Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Install dependencies
        run: sudo apt install -y ffmpeg libfftw3-dev libopus-dev libopusfile-dev libvorbis-dev libchafa-dev libfreeimage-dev libavformat-dev libstb-dev libnotify-dev

      - name: Build code
        run: make

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: ubuntu-executable-artifact
          path: ./kew

  alpine-build-check:
    name: Alpine Build Check
    runs-on: alpine-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install build essentials and dependencies
        run: |
          apk update
          apk add --no-cache \
            build-base \
            ffmpeg-dev \
            fftw-dev \
            freeimage-dev \
            chafa-dev \
            opus-dev \
            opusfile-dev \
            libvorbis-dev \
            libnotify-dev \
            glib-dev

      - name: Build code
        run: make

      - name: Upload executable artifact
        uses: actions/upload-artifact@v3
        with:
          name: alpine-executable-artifact
          path: ./kew
